### ISSUE TITLE
Tracking issue for v0.2.0 release

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/hybrid-array#74]
This is a tracking issue for a v0.2.0 release which represents a blocker for the next series of trait crate releases: https://github.com/RustCrypto/traits/issues/1571

There are no specific release blockers I am aware of. I have only held off until we are ready to start releasing trait crates just in case something else pops up which might require a breaking change.

**Comment by tarcieri** [comment]
One thing we should check before a release is that we've properly deprecated all of the old `GenericArray` methods we don't intend to support going forward

**Comment by tarcieri** [comment]
Remaining things to do:

- [ ] Refactor `extra-sizes` into smaller features that can be switched on individually
- [ ] Switch to `core::error::Error`
- [ ] Remove `std` feature

**Comment by tarcieri** [comment]
I'd say we're good to go now, though I'd like to hold off until Rust 1.82 is out before cutting a final release after merging #85.

That's scheduled for October 17th.

**Comment by jmwample** [comment]
Is there any chance of a `v0.2.0-rc.10` release before 1.82 is released next month?

**Comment by tarcieri** [comment]
Sure!

**Comment by tarcieri** [comment]
Release PR is up: #94

**Comment by tarcieri** [comment]
It's released: https://crates.io/crates/hybrid-array/0.2.0
